# Generated by Django 3.1.3 on 2021-01-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aritcle',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='aritcle',
            name='read_count',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aritcle',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='student.Tag'),
        ),
    ]
