# Generated by Django 3.1.3 on 2021-01-02 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210102_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='aritcle',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 5, 19, 41, 12276)),
        ),
    ]
